### ISSUE TITLE
Enable pdbpp configuration using pyproject.toml file

### ISSUE THREAD

**Issue by deepaerial** [pdbpp/pdbpp#484]
[pyptoject.toml](https://peps.python.org/pep-0621/) is solid standard in Python's ecosystem and majority of tools like poetry, pytest etc. allow storing all required configurations or metadata in this file. I think it would be great if pdbpp supported this standard as well so it would be possible to keep everything regarding dev environment in one place. I would expect the config section look something like this:
```toml
[tool.pdbpp]
sticky_by_default = true
editor = "nvim"
```
